name: build ESP firmware

on:
  pull_request:
    branches:
    - 'main'
  push:
    branches:
    #- 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create gitignored loginData file
      run: |
        touch src/loginData.hpp
        echo #define WifiSsid "ssid" >> src/loginData.hpp
        echo #define WifiPassword "password" >> src/loginData.hpp
        echo #define AuthKey "Bearer abc" >> src/loginData.hpp
      shell: bash

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: esp32
