name: build ESP firmware

on:
  pull_request:
    branches:
    - 'main'
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create gitignored loginData file
      run: |
        cd main
        touch loginData.hpp
        echo '#define WifiSsid "ssid"' >> loginData.hpp
        echo '#define WifiPassword "password"' >> loginData.hpp
        echo 'constexpr auto AuthKey = "Bearer abc";' >> loginData.hpp
        cat loginData.hpp
      shell: bash

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v4.4
        target: esp32
